import puppeteer from 'puppeteer-core';
const OUT = process.argv[2] ?? '.';
const browser = await puppeteer.launch({ executablePath: '/usr/bin/google-chrome', headless: true, args: ['--no-sandbox','--disable-gpu','--hide-scrollbars'], defaultViewport: { width: 1360, height: 860 } });
const page = await browser.newPage();
await page.goto('http://localhost:4173/', { waitUntil: 'networkidle0' });
await page.waitForFunction(() => window.tenbin?.builtin?.(), { timeout: 30000 });
await page.evaluate(() => { document.documentElement.setAttribute('data-theme','dark'); });
await page.evaluate(() => window.tenbin.play({ mode: 'tenbin', seats: [{type:'engine',normalId:'',fusekiId:'builtin',level:4,secPerMove:0.3},{type:'engine',normalId:'',fusekiId:'builtin',level:4,secPerMove:0.3}], names:['甲','乙'], timeControl:null }));
await page.waitForFunction(() => window.tenbin.game().moves.length >= 20, { timeout: 60000 });
await new Promise(r=>setTimeout(r,600));
await page.screenshot({ path: `${OUT}/dark-play.png` });
await page.evaluate(() => window.tenbin.game().moves.length);
console.log('ok');
await browser.close();
